{% set version = "1.0" %}

package:
  name: noqt-helpers
  version: {{ version }}


build:
  number: 1
  noarch: generic

outputs:
  - name: noqt
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('noqt5', exact=True) }}
        - {{ pin_subpackage('noqt6', exact=True) }}
    test:
      commands:
        - echo "no tests for this package"
  - name: noqt5
    build:
      noarch: generic
    requirements:
      run_constrained:
        # qt-main only exists as of 5.x
        - qt-main <5.0a0|>=6.0
        # before the creation of qt-main, a megapackage called qt existed
        - qt <0.0a0
    test:
      commands:
        - echo "no tests for this package"

  - name: noqt6
    build:
      noarch: generic
    requirements:
      run_constrained:
        # While qt-main still doesn't point to qt6, it may in the future...
        - qt-main <6.0a0
        # For qt6, we always had qt6-main
        - qt6-main <6.0a0
    test:
      commands:
        - echo "no tests for this package"

about:
  home: https://github.com/conda-forge/noqt-feedstock
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Prevents Qt installation'

extra:
  recipe-maintainers:
    - hmaarrfk
    - conda-forge/qt-main
  feedstock-name: noqt
